### ISSUE TITLE
Compilation takes almost 20 minutes

### ISSUE THREAD

**Issue by Theemuts** [meh/rust-uinput#1] opened 2016-10-10 17:56 UTC
Hi,

I'm not sure if this is a (known) issue, but I've added this library as a dependency yesterday, and if it needs to be compiled it takes nearly 20 minutes on my computer (i5 2550K, 8GB ram, Ubuntu 16.04, rustc 1.12) regardless of the compilation target. Considering that I've not had to deal with compilation times over a minute or two, this seems odd to me.

**Comment by meh** [comment] 2016-10-10 18:03
This must be a regression in rustc, it used to take some time, but not that long.

You should probably open an issue on the Rust repository.

**Comment by meh** [comment] 2016-10-10 18:04
The stuff taking time to compile is every source in `event/`, it uses the `custom_derive` crate, so it's probably because of that.

**Comment by Theemuts** [comment] 2016-10-10 18:12
Thanks for the reply, I've opened an issue in the Rust repo.

**Comment by oberien** [comment] 2017-06-05 22:37
For reference: rust-lang/rust/issues/37074

**Comment by meh** [comment] 2017-06-10 15:00
Glory to @Mark-Simulacrum, closed by https://github.com/rust-lang/rust/pull/42533.

**Closed as completed by meh** 2017-06-10 15:00 UTC
